### ISSUE TITLE
Should the ```deps``` folder go to ```.gitignore```?

### ISSUE THREAD

**Issue by sadernalwis** [B3Pay/b3-wallet#32]
Should the ```deps``` folder go to ```.gitignore```?

Seems like it generates automatically, however might have to copy```init.json``` after 
```
dfx deps pull
dfx deps init
```
because after a run, the working tree shows changes.
Have to manually remove or untrack.

**Comment by sadernalwis** [comment]
![image](https://github.com/B3Pay/b3-wallet/assets/44372160/0e38c0f9-7570-4682-b025-fb917166a0ed)


also ```yarn.lock```

**Comment by b3hr4d** [comment]
Yeah you are right, when we pull, the new II update will change the `pulled.json`.
Thank you, I'll put pulled.json, and candid folder into .gitignore.

**Comment by sadernalwis** [comment]
Nice.  what about ```yarn.lock```?
It seems to be in the ```.gitignore``` but seems to be tracked for some reason.

**Comment by b3hr4d** [comment]
Fixed with this [commit](https://github.com/B3Pay/b3-wallet/commit/f8a0e63118d2cc557ccec5565d6178b40bf08a98), that's because I didn't delete it after put "yarn.lock" inside .gitignore.

**Comment by sadernalwis** [comment]
Perfect! Closing this.
